version: '3.7'

volumes:
  data_certs:
  data_vhost:
  data_html:
  data_ftp:
  data_ftpdetc:
  data_upload:
  data_archive:
 
services:

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=- --server=127.0.0.11 --neg-ttl=3600 --cache-size=1000 --max-cache-ttl=3600 --min-cache-ttl=3600
    cap_add:
      - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    external_links:
      - pureftpd:ftp.bioatlas.se
      - proxy:archive.bioatlas.se
      - sftp:sftp.bioatlas.se

  proxy:
    image: jwilder/nginx-proxy:alpine
    init: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - data_certs:/etc/nginx/certs:ro
      - data_vhost:/etc/nginx/vhost.d
      - data_html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data_certs:/etc/nginx/certs
      - data_vhost:/etc/nginx/vhost.d
      - data_html:/usr/share/nginx/html

#https://forums.docker.com/t/docker-failing-to-correctly-process-valid-yaml-config/183/4
  sftp:
    privileged: true
    image: atmoz/sftp:alpine
    volumes:
      - ./ftpusers.conf:/etc/sftp/users.conf:ro
      - data_archive:/home/dyntaxa/
    ports:
      - "2222:22"

  webserver:
    image: nginx:alpine
    init: true
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - data_archive:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=archive.infrabas.se
      - LETSENCRYPT_HOST=archive.infrabas.se
      - LETSENCRYPT_EMAIL=roger@bioatlas.se
    depends_on:
      - sftp
      - minio
      
  minio:
    image: minio/minio:RELEASE.2019-04-23T23-50-36Z
    volumes:
     - data_archive:/data
#    ports:
#    - "9000:9000"
    env_file: ./env/.envminio
    environment:
      - VIRTUAL_HOST=minio.infrabas.se
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=minio.infrabas.se
      - LETSENCRYPT_EMAIL=roger@bioatlas.se
    command: server /data

  cron:
    image: alpine
    volumes:
      - data_archive:/data
      - ./get_dyntaxa:/etc/periodic/hourly/get_dyntaxa
    command: crond -c /etc/crontabs -S -f

  mc:
    image: minio/mc
    env_file: ./env/.envminio
    depends_on:
      - minio

